### ISSUE TITLE
"base" isn't part of the spec anymore

### ISSUE THREAD

**Issue by vitorbaptista** [datapackages/datapackage-py#31]
Check https://github.com/dataprotocols/dataprotocols/issues/232. I'm not sure if we should remove the "base" handling, given that it was removed from the spec, or keep it for backwards compatibility.

Maybe we should ignore the "base", but give a warning to the user.

**Comment by pwalsh** [comment]
@vitorbaptista I'd say we forget about backwards compatibility.
