### ISSUE TITLE
First class support for the official registry

### ISSUE THREAD

**Issue by vitorbaptista** [datapackages/datapackage-py#48]
_Imported from https://github.com/okfn/datapackage-registry-py/issues/12 (by @pwalsh)_

We have the first two options here, I'd like to introduce the 3rd, which is a simple flag to choose between the local cache and the official, live, remote registry over http.

```
# use the local cache of the official registry
registry = datapackage_registry.Registry()

# get any old registry
registry = datapackage_registry.Registry('http://someplace.com/my-registry.csv')

# work in front of the official registry instead of the local cache
registry = datapackage_registry.Registry(local=False)
```

**Comment by vitorbaptista** [comment]
I like having no special cases for the "official" registry. We don't even have its URL in the code. I reckon that with this change, the user himself won't need to know the official registry's URL, which is an improvement.

To be honest, I don't think that makes much difference, so I would rather keep the code as is, with its simpler API. However, you know the use-case better than me, so I'm happy to go with whatever you prefer.

**Comment by pwalsh** [comment]
@vitorbaptista I don't want the user to have to know the URL of the official registry. If that wasn't the case, I'd agree with you :). So yes, let's do this.

**Comment by vitorbaptista** [comment]
Side-effect of us merging with https://github.com/trickvi/datapackage/: the commits that reference issues over there are now referencing issues here.
